language: node_js
git:
  depth: 3
notifications:
  email:
    recipients:
      - soul23.4ever@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: c469e21ea9a0873c2579eb7cf529cc90a2c9eda5
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto desde Travis"
  on:
    branch: master
